# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/DCTCop/DCTCop.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DCTCop || ORIG_REF_NAME==DCTCop} -quiet] -quiet

# IP: bd/DCTCop/ip/DCTCop_microblaze_0_1/DCTCop_microblaze_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DCTCop_microblaze_0_1 || ORIG_REF_NAME==DCTCop_microblaze_0_1} -quiet] -quiet

# IP: bd/DCTCop/ip/DCTCop_dlmb_v10_1/DCTCop_dlmb_v10_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DCTCop_dlmb_v10_1 || ORIG_REF_NAME==DCTCop_dlmb_v10_1} -quiet] -quiet

# IP: bd/DCTCop/ip/DCTCop_ilmb_v10_1/DCTCop_ilmb_v10_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DCTCop_ilmb_v10_1 || ORIG_REF_NAME==DCTCop_ilmb_v10_1} -quiet] -quiet

# IP: bd/DCTCop/ip/DCTCop_dlmb_bram_if_cntlr_1/DCTCop_dlmb_bram_if_cntlr_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DCTCop_dlmb_bram_if_cntlr_1 || ORIG_REF_NAME==DCTCop_dlmb_bram_if_cntlr_1} -quiet] -quiet

# IP: bd/DCTCop/ip/DCTCop_ilmb_bram_if_cntlr_1/DCTCop_ilmb_bram_if_cntlr_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DCTCop_ilmb_bram_if_cntlr_1 || ORIG_REF_NAME==DCTCop_ilmb_bram_if_cntlr_1} -quiet] -quiet

# IP: bd/DCTCop/ip/DCTCop_lmb_bram_1/DCTCop_lmb_bram_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DCTCop_lmb_bram_1 || ORIG_REF_NAME==DCTCop_lmb_bram_1} -quiet] -quiet

# IP: bd/DCTCop/ip/DCTCop_mdm_1_1/DCTCop_mdm_1_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DCTCop_mdm_1_1 || ORIG_REF_NAME==DCTCop_mdm_1_1} -quiet] -quiet

# IP: bd/DCTCop/ip/DCTCop_clk_wiz_1_1/DCTCop_clk_wiz_1_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DCTCop_clk_wiz_1_1 || ORIG_REF_NAME==DCTCop_clk_wiz_1_1} -quiet] -quiet

# IP: bd/DCTCop/ip/DCTCop_rst_clk_wiz_1_100M_1/DCTCop_rst_clk_wiz_1_100M_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DCTCop_rst_clk_wiz_1_100M_1 || ORIG_REF_NAME==DCTCop_rst_clk_wiz_1_100M_1} -quiet] -quiet

# IP: bd/DCTCop/ip/DCTCop_DCTs_0_1/DCTCop_DCTs_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DCTCop_DCTs_0_1 || ORIG_REF_NAME==DCTCop_DCTs_0_1} -quiet] -quiet

# IP: bd/DCTCop/ip/DCTCop_xbar_1/DCTCop_xbar_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DCTCop_xbar_1 || ORIG_REF_NAME==DCTCop_xbar_1} -quiet] -quiet

# IP: bd/DCTCop/ip/DCTCop_microblaze_0_axi_periph_1/DCTCop_microblaze_0_axi_periph_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DCTCop_microblaze_0_axi_periph_1 || ORIG_REF_NAME==DCTCop_microblaze_0_axi_periph_1} -quiet] -quiet

# IP: bd/DCTCop/ip/DCTCop_axi_uartlite_0_1/DCTCop_axi_uartlite_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DCTCop_axi_uartlite_0_1 || ORIG_REF_NAME==DCTCop_axi_uartlite_0_1} -quiet] -quiet

# IP: ip/DCTs_0/DCTs_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DCTs_0 || ORIG_REF_NAME==DCTs_0} -quiet] -quiet

# XDC: bd/DCTCop/DCTCop_ooc.xdc
