# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/DCTCop/DCTCop.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DCTCop || ORIG_REF_NAME==DCTCop} -quiet] -quiet

# IP: bd/DCTCop/ip/DCTCop_microblaze_0_0/DCTCop_microblaze_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DCTCop_microblaze_0_0 || ORIG_REF_NAME==DCTCop_microblaze_0_0} -quiet] -quiet

# IP: bd/DCTCop/ip/DCTCop_DCTs_0_0/DCTCop_DCTs_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DCTCop_DCTs_0_0 || ORIG_REF_NAME==DCTCop_DCTs_0_0} -quiet] -quiet

# IP: bd/DCTCop/ip/DCTCop_dlmb_v10_0/DCTCop_dlmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DCTCop_dlmb_v10_0 || ORIG_REF_NAME==DCTCop_dlmb_v10_0} -quiet] -quiet

# IP: bd/DCTCop/ip/DCTCop_ilmb_v10_0/DCTCop_ilmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DCTCop_ilmb_v10_0 || ORIG_REF_NAME==DCTCop_ilmb_v10_0} -quiet] -quiet

# IP: bd/DCTCop/ip/DCTCop_dlmb_bram_if_cntlr_0/DCTCop_dlmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DCTCop_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==DCTCop_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/DCTCop/ip/DCTCop_ilmb_bram_if_cntlr_0/DCTCop_ilmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DCTCop_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==DCTCop_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/DCTCop/ip/DCTCop_lmb_bram_0/DCTCop_lmb_bram_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DCTCop_lmb_bram_0 || ORIG_REF_NAME==DCTCop_lmb_bram_0} -quiet] -quiet

# IP: bd/DCTCop/ip/DCTCop_xbar_0/DCTCop_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DCTCop_xbar_0 || ORIG_REF_NAME==DCTCop_xbar_0} -quiet] -quiet

# IP: bd/DCTCop/ip/DCTCop_microblaze_0_axi_periph_0/DCTCop_microblaze_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DCTCop_microblaze_0_axi_periph_0 || ORIG_REF_NAME==DCTCop_microblaze_0_axi_periph_0} -quiet] -quiet

# IP: bd/DCTCop/ip/DCTCop_microblaze_0_axi_intc_0/DCTCop_microblaze_0_axi_intc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DCTCop_microblaze_0_axi_intc_0 || ORIG_REF_NAME==DCTCop_microblaze_0_axi_intc_0} -quiet] -quiet

# IP: bd/DCTCop/ip/DCTCop_microblaze_0_xlconcat_0/DCTCop_microblaze_0_xlconcat_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DCTCop_microblaze_0_xlconcat_0 || ORIG_REF_NAME==DCTCop_microblaze_0_xlconcat_0} -quiet] -quiet

# IP: bd/DCTCop/ip/DCTCop_mdm_1_0/DCTCop_mdm_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DCTCop_mdm_1_0 || ORIG_REF_NAME==DCTCop_mdm_1_0} -quiet] -quiet

# IP: bd/DCTCop/ip/DCTCop_clk_wiz_1_0/DCTCop_clk_wiz_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DCTCop_clk_wiz_1_0 || ORIG_REF_NAME==DCTCop_clk_wiz_1_0} -quiet] -quiet

# IP: bd/DCTCop/ip/DCTCop_rst_clk_wiz_1_100M_0/DCTCop_rst_clk_wiz_1_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DCTCop_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==DCTCop_rst_clk_wiz_1_100M_0} -quiet] -quiet

# IP: bd/DCTCop/ip/DCTCop_reset_inv_0_0/DCTCop_reset_inv_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DCTCop_reset_inv_0_0 || ORIG_REF_NAME==DCTCop_reset_inv_0_0} -quiet] -quiet

# XDC: bd/DCTCop/ip/DCTCop_microblaze_0_0/DCTCop_microblaze_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==DCTCop_microblaze_0_0 || ORIG_REF_NAME==DCTCop_microblaze_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/DCTCop/ip/DCTCop_microblaze_0_0/DCTCop_microblaze_0_0_ooc_debug.xdc

# XDC: bd/DCTCop/ip/DCTCop_dlmb_v10_0/DCTCop_dlmb_v10_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==DCTCop_dlmb_v10_0 || ORIG_REF_NAME==DCTCop_dlmb_v10_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/DCTCop/ip/DCTCop_ilmb_v10_0/DCTCop_ilmb_v10_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==DCTCop_ilmb_v10_0 || ORIG_REF_NAME==DCTCop_ilmb_v10_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/DCTCop/ip/DCTCop_lmb_bram_0/DCTCop_lmb_bram_0_ooc.xdc

# XDC: bd/DCTCop/ip/DCTCop_microblaze_0_axi_intc_0/DCTCop_microblaze_0_axi_intc_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==DCTCop_microblaze_0_axi_intc_0 || ORIG_REF_NAME==DCTCop_microblaze_0_axi_intc_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/DCTCop/ip/DCTCop_microblaze_0_axi_intc_0/DCTCop_microblaze_0_axi_intc_0_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==DCTCop_microblaze_0_axi_intc_0 || ORIG_REF_NAME==DCTCop_microblaze_0_axi_intc_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/DCTCop/ip/DCTCop_microblaze_0_axi_intc_0/DCTCop_microblaze_0_axi_intc_0_ooc.xdc

# XDC: bd/DCTCop/ip/DCTCop_mdm_1_0/DCTCop_mdm_1_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==DCTCop_mdm_1_0 || ORIG_REF_NAME==DCTCop_mdm_1_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/DCTCop/ip/DCTCop_mdm_1_0/DCTCop_mdm_1_0_ooc_trace.xdc

# XDC: bd/DCTCop/ip/DCTCop_clk_wiz_1_0/DCTCop_clk_wiz_1_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==DCTCop_clk_wiz_1_0 || ORIG_REF_NAME==DCTCop_clk_wiz_1_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/DCTCop/ip/DCTCop_clk_wiz_1_0/DCTCop_clk_wiz_1_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==DCTCop_clk_wiz_1_0 || ORIG_REF_NAME==DCTCop_clk_wiz_1_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/DCTCop/ip/DCTCop_clk_wiz_1_0/DCTCop_clk_wiz_1_0_ooc.xdc

# XDC: bd/DCTCop/ip/DCTCop_rst_clk_wiz_1_100M_0/DCTCop_rst_clk_wiz_1_100M_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==DCTCop_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==DCTCop_rst_clk_wiz_1_100M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/DCTCop/ip/DCTCop_rst_clk_wiz_1_100M_0/DCTCop_rst_clk_wiz_1_100M_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==DCTCop_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==DCTCop_rst_clk_wiz_1_100M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/DCTCop/DCTCop_ooc.xdc
