#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.1 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Mon Nov 11 16:53:31 WET 2019
# SW Build 2552052 on Fri May 24 14:47:09 MDT 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xelab -wto 4a8fac7418864f96a8f126c1f323290a --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot DCT16_I_TB_behav xil_defaultlib.DCT16_I_TB -log elaborate.log"
xelab -wto 4a8fac7418864f96a8f126c1f323290a --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot DCT16_I_TB_behav xil_defaultlib.DCT16_I_TB -log elaborate.log

