webtalk_init -webtalk_dir /run/media/moinocencio/Data/Tese/TestDCTs/DCT4_AV1/DCT4_AV1.sim/sim_1/behav/xsim/xsim.dir/DCT4_TB_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Mon Nov  4 19:41:10 2019" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2019.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2552052" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "d2287765-35ef-4014-ad23-e38d26dd97cf" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "434e34417e8a42fc9a1b90b6019d22ab" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "13" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "ManjaroLinux" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Manjaro Linux" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-4510U CPU @ 2.00GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2345.154 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "801 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.02_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "123104_KB" -context "xsim\\usage"
webtalk_transmit -clientid 133055745 -regid "" -xml /run/media/moinocencio/Data/Tese/TestDCTs/DCT4_AV1/DCT4_AV1.sim/sim_1/behav/xsim/xsim.dir/DCT4_TB_behav/webtalk/usage_statistics_ext_xsim.xml -html /run/media/moinocencio/Data/Tese/TestDCTs/DCT4_AV1/DCT4_AV1.sim/sim_1/behav/xsim/xsim.dir/DCT4_TB_behav/webtalk/usage_statistics_ext_xsim.html -wdm /run/media/moinocencio/Data/Tese/TestDCTs/DCT4_AV1/DCT4_AV1.sim/sim_1/behav/xsim/xsim.dir/DCT4_TB_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
