function setGraphs
    set(    groot, ...
            'DefaultFigureColor', 'w', ...
            'DefaultAxesLineWidth', 1, ...
            'DefaultAxesXColor', 'k', ...
            'DefaultAxesYColor', 'k', ...
            'DefaultAxesFontUnits', 'points', ...
            'DefaultAxesFontSize', 20, ...
            'DefaultAxesFontName', 'Times', ...
            'DefaultLineLineWidth', 4, ...
            'DefaultTextFontUnits', 'Points', ...
            'DefaultTextFontSize', 20, ...
            'DefaultTextFontName', 'Times', ...
            'DefaultAxesBox', 'off', ...
            'DefaultAxesTickLength', [0.02 0.025]);
    % set the tickdirs to go out - need this specific order
    set(    groot, 'DefaultAxesTickDir', 'out');
    set(    groot, 'DefaultAxesTickDirMode', 'manual');
end