function setGraphs
    set(    groot, ...
            'DefaultFigureColor', 'w', ...
            'DefaultAxesLineWidth', 1, ...
            'DefaultAxesXColor', 'k', ...
            'DefaultAxesYColor', 'k', ...
            'DefaultAxesFontUnits', 'points', ...
            'DefaultAxesFontSize', 24, ...
            'DefaultAxesFontName', 'Noto Serif Medium', ...
            'DefaultLineLineWidth', 4, ...
            'DefaultTextFontUnits', 'Points', ...
            'DefaultTextFontSize', 24, ...
            'DefaultTextFontName', 'Noto Serif Medium', ...
            'DefaultAxesBox', 'off', ...
            'DefaultAxesTickLength', [0.02 0.025]);
    % set the tickdirs to go out - need this specific order
    set(    groot, 'DefaultAxesTickDir', 'out');
    set(    groot, 'DefaultAxesTickDirMode', 'manual');
    colormap(bone(10))

    set(gca,'box','off', ...
    'YGrid','on', ...
    'XGrid','off', ...
    'GridLineStyle','-');
    ax = gca;
    ax.GridAlpha = 0.7;
end