function setGraphs
    set(    groot, ...
            'DefaultFigureColor', 'w', ...
            'DefaultAxesLineWidth', 1, ...
            'DefaultAxesXColor', 'k', ...
            'DefaultAxesYColor', 'k', ...
            'DefaultAxesFontUnits', 'points', ...
            'DefaultAxesFontSize', 24, ...
            'DefaultAxesFontName', 'Times New Roman', ...
            'DefaultLineLineWidth', 4, ...
            'DefaultTextFontUnits', 'Points', ...
            'DefaultTextFontSize', 24, ...
            'DefaultTextFontName', 'Times New Roman', ...
            'DefaultAxesBox', 'off', ...
            'DefaultAxesTickLength', [0.02 0.025],...
            'defaulttextinterpreter','latex', ...
            'defaultAxesTickLabelInterpreter','latex', ...
            'defaultLegendInterpreter','latex');
    % set the tickdirs to go out - need this specific order
    set(    groot, 'DefaultAxesTickDir', 'out');
    set(    groot, 'DefaultAxesTickDirMode', 'manual');
    colormap(bone(10))

    set(gca,'box','off', ...
    'YGrid','on', ...
    'XGrid','off', ...
    'GridLineStyle','-');
    ax = gca;
    ax.GridAlpha = 0.7;
end